### ISSUE TITLE
Not working on Docker Desktop (Window)

### ISSUE THREAD

**Issue by Chavelp** [ws-skeleton/eclipse-broadway#15]
I tried it on Docker Desktop and it did not work 😞. 

It says "*** Please connect to http://172.17.0.2:5000 using your web browser ***" but I got an ERR_CONNECTION_TIMED_OUT.

Docker Desktop is for Window but containers are (of course) linux. It should work properly here but it dosn't.

**Comment by borlander** [comment]
I tried it on Docker desktop for Mac and it did not work either with the same output as reported above for Windows

**Comment by wimjongman** [comment]
Yes, @38leinaD gave the solution:

https://docs.docker.com/docker-for-windows/networking/#i-want-to-connect-to-a-container-from-windows

**Comment by mickaelistria** [comment]
Thanks @wimjongman for confirming. Let's close then as there is nothing to do in the current repo.
