### ISSUE TITLE
After stoping the container the Eclipse workspace is not coming back

### ISSUE THREAD

**Issue by azoitl** [ws-skeleton/eclipse-broadway#17]
I did some experiments with the eclipse-broadway image (e.g., installed 4diac IDE into it). However after stopping the container and restarting it I only get a import project wizard. Independent if I hit cancel or finish no Eclipse Workbench Window is shown. I tried to remove the image (I guess I did it wrongly) and cleanly pull a fresh one but the issue stays the same. 

Any tips what I could do here.

**Comment by mickaelistria** [comment]
Dup of #13
