### ISSUE TITLE
Not working with Java 8

### ISSUE THREAD

**Issue by Hanksha** [ws-skeleton/eclipse-broadway#19]
I tried to tweak the image to use Java 8 to try it out with our own RCP application which works only with Java 8. I don't see any error message in the logs but the application just doesn't start (even with the regular Eclipse IDE). 

Any idea?

I changed this line to
```
RUN dnf -y update && dnf -y install \
      dbus dbus-daemon dbus-glib \
      xorg-x11-server-utils \
      webkit2gtk3 webkit2gtk3-devel \
      mesa-libGL \
      adobe-source-code-pro-fonts abattis-cantarell-fonts \
      gnome-settings-daemon \
      wget tar \
      java-1.8.0-openjdk \
      && dnf clean all
```

I also tried to use the provided image and install Java 8 while the container is running and then restart Eclipse but same result.

**Comment by mickaelistria** [comment]
Could it be an occurrence of https://github.com/ws-skeleton/eclipse-broadway/issues/13#issuecomment-544161820 ?

**Comment by Hanksha** [comment]
I'm not sure, when I leave Java 11 in the image I can consistently get the Eclipse application started and appearing in the browser, even our own RCP application (but it's full of error due to the Java version).

**Comment by cdietrich** [comment]
shouldnt the same problem happen if you start your rcp inside linux with java 8?

**Comment by Hanksha** [comment]
I sometimes can see this error:
`Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.eclipse.swt was not provided by any .service files`

**Comment by Hanksha** [comment]
Maybe I built the image wrong.

**Comment by mickaelistria** [comment]
Ok, I'm closing the issue as we don't plan at all to support older Java versions with this specific image anyway; but we can keep chatting here.
My first question would be: why enforcing Java 8 if Java 12 works?

**Comment by Hanksha** [comment]
It's just that currently our application doesn't work with other versions than Java 8. I wanted to try out Eclipse broadway with our own application by tweaking this image to use Java 8.  Did anyone else try to build this image with Java 8?

**Comment by dihlorfos** [comment]
yeap, I've got the same issue, and my app is not compatible with java 11
