### ISSUE TITLE
SWT Browser component is not working

### ISSUE THREAD

**Issue by apupier** [ws-skeleton/eclipse-broadway#23]
there is this kind of popup:
![Screenshot from 2019-11-22 11-55-39](https://user-images.githubusercontent.com/1105127/69420479-0bb85b00-0d1f-11ea-9c95-ab5ff03aeb2d.png)

(and I cannot copy the stack due to https://github.com/ws-skeleton/eclipse-broadway/issues/18 )

**Comment by mickaelistria** [comment]
Dup of #21.

**Comment by apupier** [comment]
![Screenshot from 2019-11-22 11-58-19](https://user-images.githubusercontent.com/1105127/69420663-65b92080-0d1f-11ea-8433-df56652661b6.png)
