### ISSUE TITLE
dockerfile should have EXPOSE for each relevant port to allow using -P

### ISSUE THREAD

**Issue by maxandersen** [ws-skeleton/eclipse-broadway#4]
when running on osx or as non-priviliged it would be nice to just do `docker run -P wsskeleton/eclipse-broadway` 

plus by having EXPOSE it is self-documenting which ports that might be interesting to use -p with.

**Comment by mickaelistria** [comment]
PR welcome ;)

**Comment by mickaelistria** [comment]
Fixed.
