### ISSUE TITLE
anyway to have the rendering use modern fonts ? 

### ISSUE THREAD

**Issue by maxandersen** [ws-skeleton/eclipse-broadway#6]
when I run it now I get times new roman or something worse as the font used - anyway to enable more modern fonts by default ?

**Comment by mickaelistria** [comment]
Fonts in general seem to be the main issue with Broadway, even with newer version (many labels are even not rendered at all). All this is being investigated (as a low priority background task), but any hint, suggest, help to troubleshoot it would be welcome.

**Comment by mickaelistria** [comment]
Fixed.
